# 1 - Basic data understanding and hypothesis

In [1]:
# Importing packages

import warnings

warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Configuring matplotlib and pandas for plotting
from matplotlib.ticker import PercentFormatter
plt.rcParams.update({ "figure.figsize" : (8, 5),"axes.facecolor" : "white", "axes.edgecolor":  "black"})
plt.rcParams["figure.facecolor"]= "w"
pd.plotting.register_matplotlib_converters()
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
# Import csv into dataframe
df = pd.read_csv('data/eda.csv', delimiter=",")

## Data Understanding

### First overview of dataframe

In [3]:
# Examination of the usual suspects: head, tail, unique values etc. 
display(  
    df.info(),
    df.head(),
    df.tail(),
    df.describe()
)

# Extracting the column names as a list

column_names = df.columns.values.tolist()
print(column_names)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21597 non-null  int64  
 1   bedrooms       21597 non-null  float64
 2   bathrooms      21597 non-null  float64
 3   sqft_living    21597 non-null  float64
 4   sqft_lot       21597 non-null  float64
 5   floors         21597 non-null  float64
 6   waterfront     19206 non-null  float64
 7   view           21534 non-null  float64
 8   condition      21597 non-null  int64  
 9   grade          21597 non-null  int64  
 10  sqft_above     21597 non-null  float64
 11  sqft_basement  21145 non-null  float64
 12  yr_built       21597 non-null  int64  
 13  yr_renovated   17749 non-null  float64
 14  zipcode        21597 non-null  int64  
 15  lat            21597 non-null  float64
 16  long           21597 non-null  float64
 17  sqft_living15  21597 non-null  float64
 18  sqft_l

None

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  1000102     6.000      3.000     2400.000  9373.000   2.000         NaN   
1  1000102     6.000      3.000     2400.000  9373.000   2.000         NaN   
2  1200019     4.000      1.750     2060.000 26036.000   1.000         NaN   
3  1200021     3.000      1.000     1460.000 43000.000   1.000       0.000   
4  2800031     3.000      1.000     1430.000  7599.000   1.500       0.000   

   view  condition  grade  ...  yr_renovated  zipcode    lat     long  \
0 0.000          3      7  ...         0.000    98002 47.326 -122.214   
1 0.000          3      7  ...         0.000    98002 47.326 -122.214   
2 0.000          4      8  ...         0.000    98166 47.444 -122.351   
3 0.000          3      7  ...         0.000    98166 47.443 -122.347   
4 0.000          4      6  ...         0.000    98168 47.478 -122.265   

   sqft_living15  sqft_lot15        date      price  house_id  id.1  
0       2060.000    7316.000  2015-04-22 300000.000   1000102  2496  
1       2060.000    7316.000  2014-09-16 280000.000   1000102  2495  
2       2590.000   21891.000  2014-05-08 647500.000   1200019  6730  
3       2250.000   20023.000  2014-08-11 400000.000   1200021  8405  
4       1290.000   10320.000  2015-04-01 235000.000   2800031  8801  

[5 rows x 23 columns]

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
21592  9842300095     5.000      2.000     1600.000  4168.000   1.500   
21593  9842300485     2.000      1.000     1040.000  7372.000   1.000   
21594  9842300540     3.000      1.000     1100.000  4128.000   1.000   
21595  9895000040     2.000      1.750     1410.000  1005.000   1.500   
21596  9900000190     3.000      1.000     1320.000  8100.000   1.000   

       waterfront  view  condition  grade  ...  yr_renovated  zipcode    lat  \
21592       0.000 0.000          3      7  ...         0.000    98126 47.530   
21593       0.000 0.000          5      7  ...         0.000    98126 47.529   
21594       0.000 0.000          4      7  ...           NaN    98126 47.530   
21595       0.000 0.000          3      9  ...         0.000    98027 47.545   
21596       0.000 0.000          3      6  ...           NaN    98166 47.470   

          long  sqft_living15  sqft_lot15        date      price    house_id  \
21592 -122.381       1190.000    4168.000  2014-07-25 365000.000  9842300095   
21593 -122.378       1930.000    5150.000  2015-03-11 380000.000  9842300485   
21594 -122.379       1510.000    4538.000  2014-06-24 339000.000  9842300540   
21595 -122.018       1440.000    1188.000  2014-07-03 399900.000  9895000040   
21596 -122.351       1000.000    8100.000  2014-10-30 268950.000  9900000190   

        id.1  
21592  16724  
21593   3258  
21594   7615  
21595  20964  
21596  15938  

[5 rows x 23 columns]

id  bedrooms  bathrooms  sqft_living    sqft_lot    floors  \
count      21597.000 21597.000  21597.000    21597.000   21597.000 21597.000   
mean  4580474287.771     3.373      2.116     2080.322   15099.409     1.494   
std   2876735715.748     0.926      0.769      918.106   41412.637     0.540   
min      1000102.000     1.000      0.500      370.000     520.000     1.000   
25%   2123049175.000     3.000      1.750     1430.000    5040.000     1.000   
50%   3904930410.000     3.000      2.250     1910.000    7618.000     1.500   
75%   7308900490.000     4.000      2.500     2550.000   10685.000     2.000   
max   9900000190.000    33.000      8.000    13540.000 1651359.000     3.500   

       waterfront      view  condition     grade  ...  yr_built  yr_renovated  \
count   19206.000 21534.000  21597.000 21597.000  ... 21597.000     17749.000   
mean        0.008     0.234      3.410     7.658  ...  1971.000       836.651   
std         0.087     0.766      0.651     1.173  ...    29.375      4000.111   
min         0.000     0.000      1.000     3.000  ...  1900.000         0.000   
25%         0.000     0.000      3.000     7.000  ...  1951.000         0.000   
50%         0.000     0.000      3.000     7.000  ...  1975.000         0.000   
75%         0.000     0.000      4.000     8.000  ...  1997.000         0.000   
max         1.000     4.000      5.000    13.000  ...  2015.000     20150.000   

        zipcode       lat      long  sqft_living15  sqft_lot15       price  \
count 21597.000 21597.000 21597.000      21597.000   21597.000   21597.000   
mean  98077.952    47.560  -122.214       1986.620   12758.284  540296.574   
std      53.513     0.139     0.141        685.230   27274.442  367368.140   
min   98001.000    47.156  -122.519        399.000     651.000   78000.000   
25%   98033.000    47.471  -122.328       1490.000    5100.000  322000.000   
50%   98065.000    47.572  -122.231       1840.000    7620.000  450000.000   
75%   98118.000    47.678  -122.125       2360.000   10083.000  645000.000   
max   98199.000    47.778  -121.315       6210.000  871200.000 7700000.000   

            house_id      id.1  
count      21597.000 21597.000  
mean  4580474287.771 10799.000  
std   2876735715.748  6234.661  
min      1000102.000     1.000  
25%   2123049175.000  5400.000  
50%   3904930410.000 10799.000  
75%   7308900490.000 16198.000  
max   9900000190.000 21597.000  

[8 rows x 22 columns]

['id', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15', 'date', 'price', 'house_id', 'id.1']


### Understanding the columns

In [4]:
display(
# Understanding different values of waterfront attribute
df['waterfront'].unique(),

# Understanding different values of view attribute
df['view'].unique(),

# Understanding different values of condition attribute
df['condition'].unique(),

# Understanding different values of grade attribute
np.sort(df['grade'].unique()),

)

array([nan,  0.,  1.])

array([ 0.,  2.,  1.,  3.,  4., nan])

array([3, 4, 5, 2, 1])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])




| ID            | Explanation                            | Task?     | DT       | DT trans? | Missing values? | Other remarks:                      |
|---------------|----------------------------------------|-----------|----------|-----------|-----------------|-------------------------------------|
| id            | house id                               | drop      | int      | -         | -               | not unique due join                 |
| bedrooms      | # of bedrooms in house                 | dt transf | float    | int       |                 |                                     |
| bathrooms     | # of bathrooms in house                | dt transf | float    | int       |                 |                                     |
| sqft_living   | size of living area in squarefoot      | -         | float    | -         | no              | could be integers, seems rounded    |
| sqft_lot      | size of hole [property up to boundary](https://www.yourownarchitect.com/what-is-the-difference-between-floor-area-and-lot-area/)   | -       | float    | -         | no                |                                     |
| floors        | # of floors                            | dt transf | float    | int       |                 |                                     |
| waterfront    | is object located at waterfront        | fix       | float    | int       | yes             | 0 = no, 1 = 1                       |
| view          | # of views by interested ppl           | fix       | float    | int       | yes             | 1 to 4                              |
| condition     | rating of the object's overall condition, based on based on [King County grading system](https://info.kingcounty.gov/assessor/esales/Glossary.aspx?type=r#b)                           | -         | int      | -         | no              | 1 to 5                              |
| grade         | overall grade given to the housing unit, based on [King County grading system](https://info.kingcounty.gov/assessor/esales/Glossary.aspx?type=r#b)|           | int      |           |                 | 3 to 13                             |
| sqft_above    | size of upper levels                   | -         | float    |           |                 | could be integers, seems rounded    |
| sqft_basement | size of basement                       | -         | float    |           |                 | could be integers, seems rounded    |
| yr_built      | year house was build                   | -         | int      |           | no              | 0 and Nan, additional '0.' attached |
| yr_renovated  | year house was renovated               | fix       | float    | int       | yes                |                                     |
| zipcode       | zipcode of objects address             | -         | int      |           | no              |                                     |
| lat           | latitude of obj geographical pos.      | -         | float    |           |                 |                                     |
| long          | longitude of obj geographical pos.     | -         | float    |           |                 |                                     |
| sqft_living15 | sqft interior housing living space for nearest 15 neighbors | - | float  ||                 | could be integers, seems rounded    |
| sqft_lot15    | sqft of land lots of  nearest 15 neighbors | -     | float    |           |                 | could be integers, seems rounded    |
| date          | date transaction was conducted         | -         | datetime |           | no              |                                     |
| price         | price o. object in $                   | -         | float    |           | no              |                                     |
| house_id      | same as 'id' above                     | -         | int      |           | no              |                                     |
| id.1          | transaction id                         | Rename    | int      |           | no              |                                     |

## Assumptions and hypothesis

### Background

For this EDA task, I've chosen a buyer's profile at random. For her I'm supposed to identify matching objects, generating insights and corresponding advice.

**Nicole Johnson, Buyer**


>Looks for a lively, central neighborhood, middle price range, right timing (within a year).


### Further assumptions regarding my client:

These assumptions will potentially help to understand the client's need better and to personalize the 
* Living alone, not interested in kids in the future.
* Client's age 30 - 50; because she has already some money to work with, still interested in the lively areas of a city and not the calm suburbs.
* She not in a hurry, but kean following her dreams, hence the time frame of 1 year. As a person with a clear vision for her life, she enjoys actionable and precise recommendations.
* That could be her on [LinkedIn](https://www.linkedin.com/in/nicole-johnson-32b23a75/)

### Hypothesis
1. Time of the year will affect prices to a great extend (e.g. prices in summer 10% higher than winter). As a result buying at a specific time will save my client money
2. Lively, central neighborhoods are close to the city-center.
3. Lively, central neighborhoods are high in demand and therefore which will be shown in higher prices ranges.
4. Houses where sqft lot is more than 2% higher than sqft-living - given a 1 story object - are not in the city center 
5. Objects that get sold multiple times in 5 years are probably bad in grade and/or condition 

### Possible connection between client and attributes / Challenges after data understanding
1. "lively central neighborhood" - not represented in data
   1. Option 1: Distance to a specific long/lat of center must be calculated
   2. Option 2: use dictionary to translate all zip code to "central", "close to central", "outskirt", "far away". Do the same for "lively"
2. middle price range has to be calculated. depends on price spread
3. make assumptions when object prices are lower within a year
4. Decide whether objects with many or few transactions are are sign of quality or problems - and vice versa
5. Decide whether objects with many or few views are are sign of quality or problems - and vice versa
