In [56]:
# Imports
import numpy as np
import pandas as pd

# Importing data

df = pd.read_csv('data/eda.csv', delimiter=",")

df.head(10)

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
1  1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
2  1200019       4.0       1.75       2060.0   26036.0     1.0         NaN   
3  1200021       3.0       1.00       1460.0   43000.0     1.0         0.0   
4  2800031       3.0       1.00       1430.0    7599.0     1.5         0.0   
5  3600057       4.0       2.00       1650.0    3504.0     1.0         0.0   
6  3600072       4.0       2.75       2220.0    5310.0     1.0         NaN   
7  3800008       5.0       1.50       1990.0   18200.0     1.0         NaN   
8  5200087       4.0       2.50       2540.0    5001.0     2.0         0.0   
9  6200017       3.0       1.00       1340.0   21336.0     1.5         0.0   

   view  condition  grade  ...  yr_renovated  zipcode      lat     long  \
0   0.0          3      7  ...           0.0    98002  47.3262 -122.214   
1   0.0          3      7  ...           0.0    98002  47.3262 -122.214   
2   0.0          4      8  ...           0.0    98166  47.4444 -122.351   
3   0.0          3      7  ...           0.0    98166  47.4434 -122.347   
4   0.0          4      6  ...           0.0    98168  47.4783 -122.265   
5   0.0          3      7  ...       20130.0    98144  47.5803 -122.294   
6   0.0          5      7  ...           NaN    98144  47.5801 -122.294   
7   0.0          3      7  ...           NaN    98178  47.4938 -122.262   
8   0.0          3      9  ...           0.0    98108  47.5423 -122.302   
9   0.0          4      5  ...           0.0    98032  47.4023 -122.273   

   sqft_living15  sqft_lot15        date     price  house_id   id.1  
0         2060.0      7316.0  2015-04-22  300000.0   1000102   2496  
1         2060.0      7316.0  2014-09-16  280000.0   1000102   2495  
2         2590.0     21891.0  2014-05-08  647500.0   1200019   6730  
3         2250.0     20023.0  2014-08-11  400000.0   1200021   8405  
4         1290.0     10320.0  2015-04-01  235000.0   2800031   8801  
5         1480.0      3504.0  2015-03-19  402500.0   3600057   3554  
6         1540.0      4200.0  2015-03-30  680000.0   3600072  18507  
7         1860.0      8658.0  2015-02-24  178000.0   3800008   3198  
8         2360.0      6834.0  2014-07-09  487000.0   5200087  21048  
9         1340.0     37703.0  2014-11-12  281000.0   6200017   4330  

[10 rows x 23 columns]

## Improving columns

In [57]:
# Dropping house_id column
df = df.drop(['house_id'], axis=1)
df.head()

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
1  1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
2  1200019       4.0       1.75       2060.0   26036.0     1.0         NaN   
3  1200021       3.0       1.00       1460.0   43000.0     1.0         0.0   
4  2800031       3.0       1.00       1430.0    7599.0     1.5         0.0   

   view  condition  grade  ...  yr_built  yr_renovated  zipcode      lat  \
0   0.0          3      7  ...      1991           0.0    98002  47.3262   
1   0.0          3      7  ...      1991           0.0    98002  47.3262   
2   0.0          4      8  ...      1947           0.0    98166  47.4444   
3   0.0          3      7  ...      1952           0.0    98166  47.4434   
4   0.0          4      6  ...      1930           0.0    98168  47.4783   

      long  sqft_living15  sqft_lot15        date     price  id.1  
0 -122.214         2060.0      7316.0  2015-04-22  300000.0  2496  
1 -122.214         2060.0      7316.0  2014-09-16  280000.0  2495  
2 -122.351         2590.0     21891.0  2014-05-08  647500.0  6730  
3 -122.347         2250.0     20023.0  2014-08-11  400000.0  8405  
4 -122.265         1290.0     10320.0  2015-04-01  235000.0  8801  

[5 rows x 22 columns]

In [58]:
#Checking for missing values overall
df.isna().sum()

id                  0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2391
view               63
condition           0
grade               0
sqft_above          0
sqft_basement     452
yr_built            0
yr_renovated     3848
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
date                0
price               0
id.1                0
dtype: int64

In [59]:
# Renaming first column from id --> house id,
# renaming id.1 column to transaction_id

df = df.rename(columns={"id": "house_id", "id.1": "transaction_id"})
df.head()

house_id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
1   1000102       6.0       3.00       2400.0    9373.0     2.0         NaN   
2   1200019       4.0       1.75       2060.0   26036.0     1.0         NaN   
3   1200021       3.0       1.00       1460.0   43000.0     1.0         0.0   
4   2800031       3.0       1.00       1430.0    7599.0     1.5         0.0   

   view  condition  grade  ...  yr_built  yr_renovated  zipcode      lat  \
0   0.0          3      7  ...      1991           0.0    98002  47.3262   
1   0.0          3      7  ...      1991           0.0    98002  47.3262   
2   0.0          4      8  ...      1947           0.0    98166  47.4444   
3   0.0          3      7  ...      1952           0.0    98166  47.4434   
4   0.0          4      6  ...      1930           0.0    98168  47.4783   

      long  sqft_living15  sqft_lot15        date     price transaction_id  
0 -122.214         2060.0      7316.0  2015-04-22  300000.0           2496  
1 -122.214         2060.0      7316.0  2014-09-16  280000.0           2495  
2 -122.351         2590.0     21891.0  2014-05-08  647500.0           6730  
3 -122.347         2250.0     20023.0  2014-08-11  400000.0           8405  
4 -122.265         1290.0     10320.0  2015-04-01  235000.0           8801  

[5 rows x 22 columns]

## Cleaning cells

In [60]:
# Transforming datatype for uncomplicated columns

df = df.astype({'bedrooms': 'int32',
                'bathrooms': 'int32',
                'sqft_living': 'int32',
                'sqft_lot': 'int32',
                'floors': 'int32',
                'sqft_living15':'int32',
                'sqft_lot15':'int32'})
df.head()

house_id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   1000102         6          3         2400      9373       2         NaN   
1   1000102         6          3         2400      9373       2         NaN   
2   1200019         4          1         2060     26036       1         NaN   
3   1200021         3          1         1460     43000       1         0.0   
4   2800031         3          1         1430      7599       1         0.0   

   view  condition  grade  ...  yr_built  yr_renovated  zipcode      lat  \
0   0.0          3      7  ...      1991           0.0    98002  47.3262   
1   0.0          3      7  ...      1991           0.0    98002  47.3262   
2   0.0          4      8  ...      1947           0.0    98166  47.4444   
3   0.0          3      7  ...      1952           0.0    98166  47.4434   
4   0.0          4      6  ...      1930           0.0    98168  47.4783   

      long  sqft_living15  sqft_lot15        date     price transaction_id  
0 -122.214           2060        7316  2015-04-22  300000.0           2496  
1 -122.214           2060        7316  2014-09-16  280000.0           2495  
2 -122.351           2590       21891  2014-05-08  647500.0           6730  
3 -122.347           2250       20023  2014-08-11  400000.0           8405  
4 -122.265           1290       10320  2015-04-01  235000.0           8801  

[5 rows x 22 columns]

In [61]:
# Checking for duplicates

df.duplicated().value_counts()

False    21597
Name: count, dtype: int64

In [62]:
# fixing Waterfront
df['waterfront'].unique()

# assuming 'Nan' values are not located at a waterfront --> filling with 0
df = df.fillna({'waterfront':0})
df = df.astype({'waterfront': 'int32'})

df['waterfront'].unique()

array([0, 1], dtype=int32)

In [63]:
# fixing view
df['view'].unique()
#df.query("`view` not in [0, 1, 2, 3, 4]")

# setting 0 for NaN values
df = df.fillna({'view': 0})
df = df.astype({'view': 'int32'})

df['view'].unique()



array([0, 2, 1, 3, 4], dtype=int32)

# fixing year renovated



In [64]:
df["yr_renovated"].unique()

df['yr_renovated'] = df.yr_renovated.apply(lambda x: x/10)
df = df.fillna({'yr_renovated': 0})
df = df.astype({'yr_renovated': 'int32'})

df["yr_renovated"].unique()

array([   0, 2013, 1973, 2010, 1991, 1979, 2001, 2012, 1986, 1990, 2003,
       1962, 1992, 2006, 1940, 1955, 2007, 2014, 1989, 1982, 2005, 2000,
       1954, 1996, 2015, 1983, 1960, 1972, 1997, 1994, 1945, 2004, 1970,
       1995, 1999, 2008, 1984, 2011, 1998, 1988, 2009, 1967, 1969, 2002,
       1977, 1987, 1965, 1964, 1958, 1968, 1985, 1963, 1980, 1974, 1981,
       1950, 1956, 1957, 1993, 1975, 1946, 1948, 1978, 1976, 1934, 1959,
       1953, 1944, 1951, 1971], dtype=int32)

## fixing sqft_basement

In [65]:
df['sqft_basement'].unique()


df = df.fillna({'sqft_basement': 0})
df = df.astype({'sqft_basement': 'int32'})

df["sqft_basement"].unique()

array([   0,  900,  420,  890, 1050,  480,  330,  800,  600,  630,  990,
       1080, 1160,  210,  680, 1000, 1100,  380,  830, 1400,  930,  750,
        300,  500, 1430, 1590, 1560,  550, 1090,  700,  720, 1030,  730,
        120,  170,  400,  940,  350,  320,  530,  310,  880,  260,  620,
        580,  875,  340,  920,  430,  650,  860, 1170,  790,  570, 1060,
       1040, 1260,  950,  470, 1580,  190,  640, 2180, 1120, 1250,  710,
        590,  770, 1070, 1390,  810,  740, 1300,  960,  690, 1700,  540,
        760,  910,  780, 1940,  180,  160, 1450, 1010, 2160,  850,  840,
        410, 1140,  450,  370,  460, 1460, 1200, 1110, 1410, 1600,  360,
        220, 1500, 1540,  440, 1370,  145, 1130,  660,  820, 1470, 1480,
        280,  200,  110, 1210, 1850,  870, 1245,  560, 1420,   80,  520,
       2170,  670, 1380,  240,  140,  270,  510, 1190,  100, 1240,  250,
        130,  230,  980, 1275, 1150, 1220, 1270, 2250, 1690, 1330,  390,
         90, 1180, 1360, 3500, 1740, 2090, 1020, 12

In [66]:
df.isna().sum()

house_id          0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors            0
waterfront        0
view              0
condition         0
grade             0
sqft_above        0
sqft_basement     0
yr_built          0
yr_renovated      0
zipcode           0
lat               0
long              0
sqft_living15     0
sqft_lot15        0
date              0
price             0
transaction_id    0
dtype: int64

In [68]:
df.to_csv('data/eda_cleaned.csv')

# Ideas for additional columns

* Number of transaction per house_id
* Age
* Age of renovation
* Avg. Value of house